### PR TITLE
24 two pages only

### PR DESCRIPTION
**Pull request by nireshdhakal44**

### CODE REVIEW

**Review by DeepakBomjan — DISMISSED** [review]

**Review by nireshdhakal44 — COMMENTED** [review]
This is fine

**Review by nireshdhakal44 — COMMENTED** [review]
ok

**Comment by nireshdhakal44** [comment]
a

**Comment by nireshdhakal44** [comment]
a

**Review by DeepakBomjan — APPROVED** [review]

**Review by nireshdhakal44 — COMMENTED** [review]
ok

**Review by nireshdhakal44 — COMMENTED** [review]
ok

**Review by nireshdhakal44 — COMMENTED** [review]
a

**Pull request closed without merging**
